- id: pysentry
  name: pysentry
  description: "Fast security vulnerability scanner for Python dependencies"
  entry: pysentry-rs
  language: python
  always_run: true
  pass_filenames: false
  additional_dependencies:
    ["pysentry-rs==0.4.0", "uv==0.9.18", "pip-tools==7.5.2"]
  minimum_pre_commit_version: "2.9.2"
